{
 "title": "Dashboard de Métricas - Aplicación Web",
 "refresh": "5s",
 "panels": [
  {
   "title": "Llamadas totales - /",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    { "expr": "main_requests_total" }
   ]
  },
  {
   "title": "Llamadas totales - /logs",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "targets": [
    { "expr": "logs_requests_total" }
   ]
  },
  {
   "title": "Llamadas totales - /health",
   "type": "stat",
   "gridPos": { "x": 6, "y": 4, "w": 6, "h": 4 },
   "targets": [
    { "expr": "healthcheck_requests_total" }
   ]
  },
  {
   "title": "Llamadas totales",
   "type": "stat",
   "gridPos": { "x": 0, "y": 4, "w": 6, "h": 4 },
   "targets": [
    { "expr": "server_requests_total" }
   ]
  }
 ]
}